name: CI
on:
  push:
    branches: [ main, alpha, beta, rc/* ]
  pull_request:
    branches: [ main ]

strategy:
  matrix:
    rust: [stable, nightly]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装Rust
        uses: dtolnay/rust-toolchain@${{ matrix.rust }}
      - name: Build
        run: cargo build --all-features
      - name: Test
        run: cargo test --all-features
      - name: Clippy
        run: cargo clippy --all-features -- -D warnings
      - name: Format check
        run: cargo fmt --check --all
